" ------- SOURCING -------
" Ensures Vim-Plug is sourced
if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" ------- GENERAL -------
let mapleader = " "
set nocompatible
filetype plugin on
syntax on

" ------- PLUGINS -------
call plug#begin('~/.config/vim/plugged')
Plug 'git@github.com:sheerun/vim-polyglot.git' " Use the ssh URL
Plug 'git@github.com:sainnhe/everforest.git' " Colorscheme
Plug 'git@github.com:preservim/nerdtree.git' " File Tree
Plug 'git@github.com:prabirshrestha/vim-lsp.git' " LSP 
Plug 'git@github.com:mattn/vim-lsp-settings.git' " LSP helper
Plug 'git@github.com:prabirshrestha/asyncomplete-lsp.vim.git' " LSP & Auto Helper
Plug 'git@github.com:prabirshrestha/asyncomplete.vim.git' " Autocomplete
Plug 'git@github.com:vim-airline/vim-airline.git' " Status Line
Plug 'git@github.com:ryanoasis/vim-devicons.git' " Devicons
Plug 'git@github.com:vimwiki/vimwiki.git' "Vimwiki for Notes
call plug#end()

" -------- UI --------
" Editor
set encoding=UTF-8
set number
set relativenumber
set tabstop=4

" Color Scheme
set termguicolors
set background=dark
let g:everforest_background = 'medium'
let g:everforest_better_performance = 1
colorscheme everforest
hi Normal guibg=NONE
hi NormalNC guibg=NONE

" Nerd Tree
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFocus<CR>
let NERDTreeShowHidden=1

" ------- LSP & Friends -------
"  Vim LSP auto installation
let g:lsp_settings_auto_install = 1
nnoremap <leader>ls :LspInstallServer<CR>
if executable('gopls')
    " go install golang.org/x/tools/gopls@latest
    au User lsp_setup call lsp#register_server({
        \ 'name': 'gopls',
        \ 'cmd': {server_info->['gopls']},
        \ 'allowlist': ['go'],
        \ })
endif

"  Autocomplete
autocmd! User asyncomplete_setup call asyncomplete#register_source({
      \ 'name': 'lsp',
      \ 'allowlist': ['*'],
      \ 'completor': function('asyncomplete#sources#lsp#completor')
      \ })

" ------- VimWiki -------

let g:vimwiki_list = [{'path': '/home/kalli/Insync/sea.gilbert002@gmail.com/Google\ Drive/Personal/vimwiki',
                      \ 'syntax': 'markdown', 'ext': 'md'}]
nnoremap <leader>w<leader>n :VimwikiMakeTomorrowDiaryNote
nnoremap <leader>dp :VimwikiDiaryGenerateLinks
